# Generated by Django 6.1 on 2026-08-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_alter_message_options_message_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_email',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('email', 'Gmail')]),
        ),
    ]
