# Generated by Django 6.1 on 2026-09-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_message_user_email_alter_message_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
