# Generated by Django 6.1 on 2026-09-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_alter_message_options_remove_message_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
