# Generated by Django 6.1 on 2026-09-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0008_assign_messenger_messages_to_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
