# Generated by Django 6.1 on 2026-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0011_message_indexes_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_id',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
    ]
