# Generated by Django 6.1 on 2026-09-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0012_add_contact_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='inbox_messa_user_em_7c6a2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='inbox_messa_channel_0d3b4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='inbox_messa_created_9f2d6e_idx',
        ),
    ]
